spring.application.name=SysTrackPro
server.port=8080
server.servlet.context-path=/systrack

# MySQL Connection Settings
spring.datasource.url=jdbc:mysql://localhost:3306/systrack_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Root@123
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver

# Hibernate Settings for MySQL
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update

# SQL Initialization Settings (Keep data.sql parsing active if needed)
spring.sql.init.mode=never
spring.jpa.defer-datasource-initialization=false